In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('large_messy_dataset_option2.csv')

In [3]:
df

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [4]:
df.isnull()

     CustomerID   Name    Age  Salary   City  Email  JoiningDate
0         False  False   True   False   True  False        False
1         False  False  False    True   True  False        False
2         False  False   True   False  False  False        False
3         False  False  False   False  False  False        False
4         False  False   True   False  False  False        False
..          ...    ...    ...     ...    ...    ...          ...
295       False  False  False   False  False  False         True
296       False  False  False   False  False  False        False
297       False  False  False   False  False  False        False
298       False  False   True   False  False  False        False
299       False  False   True    True  False  False        False

[300 rows x 7 columns]

In [5]:
df.isnull().sum()

CustomerID      0
Name            0
Age            75
Salary         73
City           49
Email           0
JoiningDate    66
dtype: int64

In [6]:
#df["Age"].fillna(0)
#df["Age"].fillna(0, inplace=True)
#df["Salary"].fillna(df["Salary"].mean(), inplace=True)
#df["City"].fillna(df["City"].mode()[0], inplace=True)
#df.dropna()
#df.dropna(axis=1)
#df.dropna(thresh=3)
#df.duplicated()
#df.duplicated().sum()
#df.drop_duplicates(subset=["Name"])
#df[df['JoiningDate'].isnull()==True]
#df.loc[df['JoiningDate'].isna()]
#df.dropna(subset=['JoiningDate'], inplace=True)

In [16]:
df['JoiningDate'].isnull().sum()

66

In [26]:
df[df['JoiningDate'].isnull()==False, inplace=True]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (932833671.py, line 1)