In [31]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [4]:
all_data = []

In [5]:
for page in range(1, 6):
    url = f"http://quotes.toscrape.com/page/{page}/"
    
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    
    quotes = soup.find_all("div", class_="quote")
    
    for q in quotes:
        quote = q.find("span", class_="text").text
        author = q.find("small", class_="author").text
        
        all_data.append({
            "quote": quote,
            "author": author
        })

In [6]:
print(len(all_data))

50

In [18]:
print(all_data[0]['quote'].strip('“”'))
print(all_data[0]['author'].strip('“”'))

The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.
Albert Einstein

In [20]:
for i in range(len(all_data)):
    print(all_data[i]['quote'].strip('“”'))
    print(all_data[i]['author'].strip('“”'))
    print('-'*50)

The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.
Albert Einstein
--------------------------------------------------
It is our choices, Harry, that show what we truly are, far more than our abilities.
J.K. Rowling
--------------------------------------------------
There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.
Albert Einstein
--------------------------------------------------
The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.
Jane Austen
--------------------------------------------------
Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.
Marilyn Monroe
--------------------------------------------------
Try not to become a man of success. Rather become a man of value.
Albert Einstein
--------------------------------------------------
It is better to be hated for what you are than to be loved for what you are not.
André Gide
--------------------------------------------------
I have not failed. I've just found 10,000 ways that won't work.
Thomas A. Edison
--------------------------------------------------
A woman is like a tea bag; you never know how strong it is until it's in hot water.
Eleanor Roosevelt
--------------------------------------------------
A day without sunshine is like, you know, night.
Steve Martin
--------------------------------------------------
This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.
Marilyn Monroe
--------------------------------------------------
It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.
J.K. Rowling
--------------------------------------------------
If you can't explain it to a six year old, you don't understand it yourself.
Albert Einstein
--------------------------------------------------
You may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect—you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break—her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there.
Bob Marley
--------------------------------------------------
I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.
Dr. Seuss
--------------------------------------------------
I may not have gone where I intended to go, but I think I have ended up where I needed to be.
Douglas Adams
--------------------------------------------------
The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.
Elie Wiesel
--------------------------------------------------
It is not a lack of love, but a lack of friendship that makes unhappy marriages.
Friedrich Nietzsche
--------------------------------------------------
Good friends, good books, and a sleepy conscience: this is the ideal life.
Mark Twain
--------------------------------------------------
Life is what happens to us while we are making other plans.
Allen Saunders
--------------------------------------------------
I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.
Pablo Neruda
--------------------------------------------------
For every minute you are angry you lose sixty seconds of happiness.
Ralph Waldo Emerson
--------------------------------------------------
If you judge people, you have no time to love them.
Mother Teresa
--------------------------------------------------
Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.
Garrison Keillor
--------------------------------------------------
Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.
Jim Henson
--------------------------------------------------
Today you are You, that is truer than true. There is no one alive who is Youer than You.
Dr. Seuss
--------------------------------------------------
If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.
Albert Einstein
--------------------------------------------------
It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all - in which case, you fail by default.
J.K. Rowling
--------------------------------------------------
Logic will get you from A to Z; imagination will get you everywhere.
Albert Einstein
--------------------------------------------------
One good thing about music, when it hits you, you feel no pain.
Bob Marley
--------------------------------------------------
The more that you read, the more things you will know. The more that you learn, the more places you'll go.
Dr. Seuss
--------------------------------------------------
Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?
J.K. Rowling
--------------------------------------------------
The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.
Bob Marley
--------------------------------------------------
Not all of us can do great things. But we can do small things with great love.
Mother Teresa
--------------------------------------------------
To the well-organized mind, death is but the next great adventure.
J.K. Rowling
--------------------------------------------------
All you need is love. But a little chocolate now and then doesn't hurt.
Charles M. Schulz
--------------------------------------------------
We read to know we're not alone.
William Nicholson
--------------------------------------------------
Any fool can know. The point is to understand.
Albert Einstein
--------------------------------------------------
I have always imagined that Paradise will be a kind of library.
Jorge Luis Borges
--------------------------------------------------
It is never too late to be what you might have been.
George Eliot
--------------------------------------------------
A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.
George R.R. Martin
--------------------------------------------------
You can never get a cup of tea large enough or a book long enough to suit me.
C.S. Lewis
--------------------------------------------------
You believe lies so you eventually learn to trust no one but yourself.
Marilyn Monroe
--------------------------------------------------
If you can make a woman laugh, you can make her do anything.
Marilyn Monroe
--------------------------------------------------
Life is like riding a bicycle. To keep your balance, you must keep moving.
Albert Einstein
--------------------------------------------------
The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.
Marilyn Monroe
--------------------------------------------------
A wise girl kisses but doesn't love, listens but doesn't believe, and leaves before she is left.
Marilyn Monroe
--------------------------------------------------
Only in the darkness can you see the stars.
Martin Luther King Jr.
--------------------------------------------------
It matters not what someone is born, but what they grow to be.
J.K. Rowling
--------------------------------------------------
Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.
James Baldwin
--------------------------------------------------

In [21]:

base_url = "http://quotes.toscrape.com"

all_data = []
author_cache = {}

for page in range(1, 6):
    url = f"{base_url}/page/{page}/"
    
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    
    quotes = soup.find_all("div", class_="quote")
    
    for q in quotes:
        quote = q.find("span", class_="text").text
        author = q.find("small", class_="author").text
        
        tags = [tag.text for tag in q.find_all("a", class_="tag")]
        
        author_link = q.find("a")["href"]
        full_author_url = base_url + author_link
        
        # 🔥 Cache check
        if author in author_cache:
            about = author_cache[author]
        else:
            author_response = requests.get(full_author_url)
            author_soup = BeautifulSoup(author_response.text, "html.parser")
            
            about = author_soup.find("div", class_="author-description").text.strip()
            
            author_cache[author] = about
        
        all_data.append({
            "quote": quote,
            "author": author,
            "tags": tags,
            "about": about
        })

print(len(all_data))

50

In [30]:
for i in range(len(all_data)):
    print(all_data[i]['quote'].strip('“”'))
    print(all_data[i]['author'].strip('“”'))
    print(all_data[i]['tags'])
    print(all_data[i]['about'].strip('“”'))
    print('*'*50)

The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.
Albert Einstein
['change', 'deep-thoughts', 'thinking', 'world']
In 1879, Albert Einstein was born in Ulm, Germany. He completed his Ph.D. at the University of Zurich by 1909. His 1905 paper explaining the photoelectric effect, the basis of electronics, earned him the Nobel Prize in 1921. His first paper on Special Relativity Theory, also published in 1905, changed the world. After the rise of the Nazi party, Einstein made Princeton his permanent home, becoming a U.S. citizen in 1940. Einstein, a pacifist during World War I, stayed a firm proponent of social justice and responsibility. He chaired the Emergency Committee of Atomic Scientists, which organized to alert the public to the dangers of atomic warfare.At a symposium, he advised: "In their struggle for the ethical good, teachers of religion must have the stature to give up the doctrine of a personal God, that is, give up that source of fear and hope which in the past placed such vast power in the hands of priests. In their labors they will have to avail themselves of those forces which are capable of cultivating the Good, the True, and the Beautiful in humanity itself. This is, to be sure a more difficult but an incomparably more worthy task . . . " ("Science, Philosophy and Religion, A Symposium," published by the Conference on Science, Philosophy and Religion in their Relation to the Democratic Way of Life, Inc., New York, 1941). In a letter to philosopher Eric Gutkind, dated Jan. 3, 1954, Einstein stated: "The word god is for me nothing more than the expression and product of human weaknesses, the Bible a collection of honorable, but still primitive legends which are nevertheless pretty childish. No interpretation no matter how subtle can (for me) change this," (The Guardian, "Childish superstition: Einstein's letter makes view of religion relatively clear," by James Randerson, May 13, 2008). D. 1955.While best known for his mass–energy equivalence formula E = mc2 (which has been dubbed "the world's most famous equation"), he received the 1921 Nobel Prize in Physics "for his services to theoretical physics, and especially for his discovery of the law of the photoelectric effect". The latter was pivotal in establishing quantum theory.Einstein thought that Newtonion mechanics was no longer enough to reconcile the laws of classical mechanics with the laws of the electromagnetic field. This led to the development of his special theory of relativity. He realized, however, that the principle of relativity could also be extended to gravitational fields, and with his subsequent theory of gravitation in 1916, he published a paper on the general theory of relativity. He continued to deal with problems of statistical mechanics and quantum theory, which led to his explanations of particle theory and the motion of molecules. He also investigated the thermal properties of light which laid the foundation of the photon theory of light.He was visiting the United States when Adolf Hitler came to power in 1933 and did not go back to Germany. On the eve of World War II, he endorsed a letter to President Franklin D. Roosevelt alerting him to the potential development of "extremely powerful bombs of a new type" and recommending that the U.S. begin similar research. This eventually led to what would become the Manhattan Project. Einstein supported defending the Allied forces, but largely denounced the idea of using the newly discovered nuclear fission as a weapon. Later, with Bertrand Russell, Einstein signed the Russell–Einstein Manifesto, which highlighted the danger of nuclear weapons. Einstein was affiliated with the Institute for Advanced Study in Princeton, New Jersey, until his death in 1955.His great intellectual achievements and originality have made the word "Einstein" synonymous with genius.More: http://en.wikipedia.org/wiki/Albert_E...http://www.nobelprize.org/nobel_prize...
**************************************************
It is our choices, Harry, that show what we truly are, far more than our abilities.
J.K. Rowling
['abilities', 'choices']
See also: Robert GalbraithAlthough she writes under the pen name J.K. Rowling, pronounced like rolling, her name when her first Harry Potter book was published was simply Joanne Rowling. Anticipating that the target audience of young boys might not want to read a book written by a woman, her publishers demanded that she use two initials, rather than her full name. As she had no middle name, she chose K as the second initial of her pen name, from her paternal grandmother Kathleen Ada Bulgen Rowling. She calls herself Jo and has said, "No one ever called me 'Joanne' when I was young, unless they were angry." Following her marriage, she has sometimes used the name Joanne Murray when conducting personal business. During the Leveson Inquiry she gave evidence under the name of Joanne Kathleen Rowling. In a 2012 interview, Rowling noted that she no longer cared that people pronounced her name incorrectly.Rowling was born to Peter James Rowling, a Rolls-Royce aircraft engineer, and Anne Rowling (née Volant), on 31 July 1965 in Yate, Gloucestershire, England, 10 miles (16 km) northeast of Bristol. Her mother Anne was half-French and half-Scottish. Her parents first met on a train departing from King's Cross Station bound for Arbroath in 1964. They married on 14 March 1965. Her mother's maternal grandfather, Dugald Campbell, was born in Lamlash on the Isle of Arran. Her mother's paternal grandfather, Louis Volant, was awarded the Croix de Guerre for exceptional bravery in defending the village of Courcelles-le-Comte during the First World War.Rowling's sister Dianne was born at their home when Rowling was 23 months old. The family moved to the nearby village Winterbourne when Rowling was four. She attended St Michael's Primary School, a school founded by abolitionist William Wilberforce and education reformer Hannah More. Her headmaster at St Michael's, Alfred Dunn, has been suggested as the inspiration for the Harry Potter headmaster Albus Dumbledore.As a child, Rowling often wrote fantasy stories, which she would usually then read to her sister. She recalls that: "I can still remember me telling her a story in which she fell down a rabbit hole and was fed strawberries by the rabbit family inside it. Certainly the first story I ever wrote down (when I was five or six) was about a rabbit called Rabbit. He got the measles and was visited by his friends, including a giant bee called Miss Bee." At the age of nine, Rowling moved to Church Cottage in the Gloucestershire village of Tutshill, close to Chepstow, Wales. When she was a young teenager, her great aunt, who Rowling said "taught classics and approved of a thirst for knowledge, even of a questionable kind," gave her a very old copy of Jessica Mitford's autobiography, Hons and Rebels. Mitford became Rowling's heroine, and Rowling subsequently read all of her books.Rowling has said of her teenage years, in an interview with The New Yorker, "I wasn’t particularly happy. I think it’s a dreadful time of life." She had a difficult homelife; her mother was ill and she had a difficult relationship with her father (she is no longer on speaking terms with him). She attended secondary school at Wyedean School and College, where her mother had worked as a technician in the science department. Rowling said of her adolescence, "Hermione [a bookish, know-it-all Harry Potter character] is loosely based on me. She's a caricature of me when I was eleven, which I'm not particularly proud of." Steve Eddy, who taught Rowling English when she first arrived, remembers her as "not exceptional" but "one of a group of girls who were bright, and quite good at English." Sean Harris, her best friend in the Upper Sixth owned a turquoise Ford Anglia, which she says inspired the one in her books.
**************************************************
There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.
Albert Einstein
['inspirational', 'life', 'live', 'miracle', 'miracles']
In 1879, Albert Einstein was born in Ulm, Germany. He completed his Ph.D. at the University of Zurich by 1909. His 1905 paper explaining the photoelectric effect, the basis of electronics, earned him the Nobel Prize in 1921. His first paper on Special Relativity Theory, also published in 1905, changed the world. After the rise of the Nazi party, Einstein made Princeton his permanent home, becoming a U.S. citizen in 1940. Einstein, a pacifist during World War I, stayed a firm proponent of social justice and responsibility. He chaired the Emergency Committee of Atomic Scientists, which organized to alert the public to the dangers of atomic warfare.At a symposium, he advised: "In their struggle for the ethical good, teachers of religion must have the stature to give up the doctrine of a personal God, that is, give up that source of fear and hope which in the past placed such vast power in the hands of priests. In their labors they will have to avail themselves of those forces which are capable of cultivating the Good, the True, and the Beautiful in humanity itself. This is, to be sure a more difficult but an incomparably more worthy task . . . " ("Science, Philosophy and Religion, A Symposium," published by the Conference on Science, Philosophy and Religion in their Relation to the Democratic Way of Life, Inc., New York, 1941). In a letter to philosopher Eric Gutkind, dated Jan. 3, 1954, Einstein stated: "The word god is for me nothing more than the expression and product of human weaknesses, the Bible a collection of honorable, but still primitive legends which are nevertheless pretty childish. No interpretation no matter how subtle can (for me) change this," (The Guardian, "Childish superstition: Einstein's letter makes view of religion relatively clear," by James Randerson, May 13, 2008). D. 1955.While best known for his mass–energy equivalence formula E = mc2 (which has been dubbed "the world's most famous equation"), he received the 1921 Nobel Prize in Physics "for his services to theoretical physics, and especially for his discovery of the law of the photoelectric effect". The latter was pivotal in establishing quantum theory.Einstein thought that Newtonion mechanics was no longer enough to reconcile the laws of classical mechanics with the laws of the electromagnetic field. This led to the development of his special theory of relativity. He realized, however, that the principle of relativity could also be extended to gravitational fields, and with his subsequent theory of gravitation in 1916, he published a paper on the general theory of relativity. He continued to deal with problems of statistical mechanics and quantum theory, which led to his explanations of particle theory and the motion of molecules. He also investigated the thermal properties of light which laid the foundation of the photon theory of light.He was visiting the United States when Adolf Hitler came to power in 1933 and did not go back to Germany. On the eve of World War II, he endorsed a letter to President Franklin D. Roosevelt alerting him to the potential development of "extremely powerful bombs of a new type" and recommending that the U.S. begin similar research. This eventually led to what would become the Manhattan Project. Einstein supported defending the Allied forces, but largely denounced the idea of using the newly discovered nuclear fission as a weapon. Later, with Bertrand Russell, Einstein signed the Russell–Einstein Manifesto, which highlighted the danger of nuclear weapons. Einstein was affiliated with the Institute for Advanced Study in Princeton, New Jersey, until his death in 1955.His great intellectual achievements and originality have made the word "Einstein" synonymous with genius.More: http://en.wikipedia.org/wiki/Albert_E...http://www.nobelprize.org/nobel_prize...
**************************************************
The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.
Jane Austen
['aliteracy', 'books', 'classic', 'humor']
Jane Austen was an English novelist whose works of romantic fiction, set among the landed gentry, earned her a place as one of the most widely read writers in English literature, her realism and biting social commentary cementing her historical importance among scholars and critics.Austen lived her entire life as part of a close-knit family located on the lower fringes of the English landed gentry. She was educated primarily by her father and older brothers as well as through her own reading. The steadfast support of her family was critical to her development as a professional writer. Her artistic apprenticeship lasted from her teenage years until she was about 35 years old. During this period, she experimented with various literary forms, including the epistolary novel which she tried then abandoned, and wrote and extensively revised three major novels and began a fourth. From 1811 until 1816, with the release of Sense and Sensibility (1811), Pride and Prejudice (1813), Mansfield Park (1814) and Emma (1815), she achieved success as a published writer. She wrote two additional novels, Northanger Abbey and Persuasion, both published posthumously in 1818, and began a third, which was eventually titled Sanditon, but died before completing it.Austen's works critique the novels of sensibility of the second half of the 18th century and are part of the transition to 19th-century realism. Her plots, though fundamentally comic, highlight the dependence of women on marriage to secure social standing and economic security. Her work brought her little personal fame and only a few positive reviews during her lifetime, but the publication in 1869 of her nephew's A Memoir of Jane Austen introduced her to a wider public, and by the 1940s she had become widely accepted in academia as a great English writer. The second half of the 20th century saw a proliferation of Austen scholarship and the emergence of a Janeite fan culture.
**************************************************
Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.
Marilyn Monroe
['be-yourself', 'inspirational']
Marilyn Monroe (born Norma Jeane Mortenson; June 1, 1926 – August 5, 1962) was an American actress, model, and singer, who became a major sex symbol, starring in a number of commercially successful motion pictures during the 1950s and early 1960s.After spending much of her childhood in foster homes, Monroe began a career as a model, which led to a film contract in 1946 with Twentieth Century-Fox. Her early film appearances were minor, but her performances in The Asphalt Jungle and All About Eve (both 1950), drew attention. By 1952 she had her first leading role in Don't Bother to Knock and 1953 brought a lead in Niagara, a melodramatic film noir that dwelt on her seductiveness. Her "dumb blonde" persona was used to comic effect in subsequent films such as Gentlemen Prefer Blondes (1953), How to Marry a Millionaire (1953) and The Seven Year Itch (1955). Limited by typecasting, Monroe studied at the Actors Studio to broaden her range. Her dramatic performance in Bus Stop (1956) was hailed by critics and garnered a Golden Globe nomination. Her production company, Marilyn Monroe Productions, released The Prince and the Showgirl (1957), for which she received a BAFTA Award nomination and won a David di Donatello award. She received a Golden Globe Award for her performance in Some Like It Hot (1959). Monroe's last completed film was The Misfits, co-starring Clark Gable with screenplay by her then-husband, Arthur Miller.Marilyn was a passionate reader, owning four hundred books at the time of her death, and was often photographed with a book.The final years of Monroe's life were marked by illness, personal problems, and a reputation for unreliability and being difficult to work with. The circumstances of her death, from an overdose of barbiturates, have been the subject of conjecture. Though officially classified as a "probable suicide", the possibility of an accidental overdose, as well as of homicide, have not been ruled out. In 1999, Monroe was ranked as the sixth greatest female star of all time by the American Film Institute. In the decades following her death, she has often been cited as both a pop and a cultural icon as well as the quintessential American sex symbol.
**************************************************
Try not to become a man of success. Rather become a man of value.
Albert Einstein
['adulthood', 'success', 'value']

In [32]:
df=pd.DataFrame(all_data)

In [33]:
df

,quote,author,tags,about
0,“The world as we have created it is a process ...,Albert Einstein,"[change, deep-thoughts, thinking, world]","In 1879, Albert Einstein was born in Ulm, Germ..."
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"[abilities, choices]",See also: Robert GalbraithAlthough she writes ...
2,“There are only two ways to live your life. On...,Albert Einstein,"[inspirational, life, live, miracle, miracles]","In 1879, Albert Einstein was born in Ulm, Germ..."
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"[aliteracy, books, classic, humor]",Jane Austen was an English novelist whose work...
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"[be-yourself, inspirational]",Marilyn Monroe (born Norma Jeane Mortenson; Ju...
5,“Try not to become a man of success. Rather be...,Albert Einstein,"[adulthood, success, value]","In 1879, Albert Einstein was born in Ulm, Germ..."
6,“It is better to be hated for what you are tha...,André Gide,"[life, love]",André Paul Guillaume Gide was a French author ...
7,"“I have not failed. I've just found 10,000 way...",Thomas A. Edison,"[edison, failure, inspirational, paraphrased]","Thomas Alva Edison was an American inventor, s..."
8,“A woman is like a tea bag; you never know how...,Eleanor Roosevelt,[misattributed-eleanor-roosevelt],Anna Eleanor Roosevelt was an American politic...
9,"“A day without sunshine is like, you know, nig...",Steve Martin,"[humor, obvious, simile]","Stephen Glenn ""Steve"" Martin is an American ac..."
10,“This life is what you make it. No matter what...,Marilyn Monroe,"[friends, heartbreak, inspirational, life, lov...",Marilyn Monroe (born Norma Jeane Mortenson; Ju...
11,“It takes a great deal of bravery to stand up ...,J.K. Rowling,"[courage, friends]",See also: Robert GalbraithAlthough she writes ...
12,"“If you can't explain it to a six year old, yo...",Albert Einstein,"[simplicity, understand]","In 1879, Albert Einstein was born in Ulm, Germ..."
13,"“You may not be her first, her last, or her on...",Bob Marley,[love],"Robert ""Bob"" Nesta Marley OM was a Jamaican si..."
14,"“I like nonsense, it wakes up the brain cells....",Dr. Seuss,[fantasy],Theodor Seuss Geisel was born 2 March 1904 in ...
15,"“I may not have gone where I intended to go, b...",Douglas Adams,"[life, navigation]","Douglas Noël Adams was an English author, comi..."
16,"“The opposite of love is not hate, it's indiff...",Elie Wiesel,"[activism, apathy, hate, indifference, inspira...",Eliezer Wiesel was a Romania-born American nov...
17,"“It is not a lack of love, but a lack of frien...",Friedrich Nietzsche,"[friendship, lack-of-friendship, lack-of-love,...",Friedrich Wilhelm Nietzsche (1844–1900) is a G...
18,"“Good friends, good books, and a sleepy consci...",Mark Twain,"[books, contentment, friends, friendship, life]","Samuel Langhorne Clemens, better known by his ..."
19,“Life is what happens to us while we are makin...,Allen Saunders,"[fate, life, misattributed-john-lennon, planni...","Allen Saunders was an American writer, journal..."
20,"“I love you without knowing how, or when, or f...",Pablo Neruda,"[love, poetry]","Pablo Neruda was the pen name and, later, lega..."
21,“For every minute you are angry you lose sixty...,Ralph Waldo Emerson,[happiness],"in 1803, Ralph Waldo Emerson was born in Bosto..."
22,"“If you judge people, you have no time to love...",Mother Teresa,[attributed-no-source],"Blessed Teresa of Calcutta, or Mother Teresa, ..."
23,“Anyone who thinks sitting in church can make ...,Garrison Keillor,"[humor, religion]",Garrison Keillor (born Gary Edward Keillor on ...
24,“Beauty is in the eye of the beholder and it m...,Jim Henson,[humor],"James Maury ""Jim"" Henson was the most widely k..."
25,"“Today you are You, that is truer than true. T...",Dr. Seuss,"[comedy, life, yourself]",Theodor Seuss Geisel was born 2 March 1904 in ...
26,"“If you want your children to be intelligent, ...",Albert Einstein,"[children, fairy-tales]","In 1879, Albert Einstein was born in Ulm, Germ..."
27,“It is impossible to live without failing at s...,J.K. Rowling,[],See also: Robert GalbraithAlthough she writes ...
28,“Logic will get you from A to Z; imagination w...,Albert Einstein,[imagination],"In 1879, Albert Einstein was born in Ulm, Germ..."
29,"“One good thing about music, when it hits you,...",Bob Marley,[music],"Robert ""Bob"" Nesta Marley OM was a Jamaican si..."
30,"“The more that you read, the more things you w...",Dr. Seuss,"[learning, reading, seuss]",Theodor Seuss Geisel was born 2 March 1904 in ...
31,"“Of course it is happening inside your head, H...",J.K. Rowling,[dumbledore],See also: Robert GalbraithAlthough she writes ...
32,"“The truth is, everyone is going to hurt you. ...",Bob Marley,[friendship],"Robert ""Bob"" Nesta Marley OM was a Jamaican si..."
33,“Not all of us can do great things. But we can...,Mother Teresa,"[misattributed-to-mother-teresa, paraphrased]","Blessed Teresa of Calcutta, or Mother Teresa, ..."
34,"“To the well-organized mind, death is but the ...",J.K. Rowling,"[death, inspirational]",See also: Robert GalbraithAlthough she writes ...
35,“All you need is love. But a little chocolate ...,Charles M. Schulz,"[chocolate, food, humor]",Charles Monroe Schulz was an American cartooni...
36,“We read to know we're not alone.”,William Nicholson,"[misattributed-to-c-s-lewis, reading]",Librarian Note: There is more than one author ...
37,“Any fool can know. The point is to understand.”,Albert Einstein,"[knowledge, learning, understanding, wisdom]","In 1879, Albert Einstein was born in Ulm, Germ..."
38,“I have always imagined that Paradise will be ...,Jorge Luis Borges,"[books, library]",Jorge Francisco Isidoro Luis Borges Acevedo (S...
39,“It is never too late to be what you might hav...,George Eliot,[inspirational],"In 1819, novelist George Eliot (nee Mary Ann E..."
40,“A reader lives a thousand lives before he die...,George R.R. Martin,"[read, readers, reading, reading-books]","George R. R. Martin was born September 20, 194..."
41,“You can never get a cup of tea large enough o...,C.S. Lewis,"[books, inspirational, reading, tea]",CLIVE STAPLES LEWIS (1898–1963) was one of the...
42,“You believe lies so you eventually learn to t...,Marilyn Monroe,[],Marilyn Monroe (born Norma Jeane Mortenson; Ju...
43,"“If you can make a woman laugh, you can make h...",Marilyn Monroe,"[girls, love]",Marilyn Monroe (born Norma Jeane Mortenson; Ju...
44,“Life is like riding a bicycle. To keep your b...,Albert Einstein,"[life, simile]","In 1879, Albert Einstein was born in Ulm, Germ..."
45,“The real lover is the man who can thrill you ...,Marilyn Monroe,[love],Marilyn Monroe (born Norma Jeane Mortenson; Ju...
46,"“A wise girl kisses but doesn't love, listens ...",Marilyn Monroe,[attributed-no-source],Marilyn Monroe (born Norma Jeane Mortenson; Ju...
47,“Only in the darkness can you see the stars.”,Martin Luther King Jr.,"[hope, inspirational]","Martin Luther King, Jr. was one of the pivotal..."
48,"“It matters not what someone is born, but what...",J.K. Rowling,[dumbledore],See also: Robert GalbraithAlthough she writes ...
49,“Love does not begin and end the way we seem t...,James Baldwin,[love],Librarian Note: There is more than one author ...

In [35]:
rows = []

for item in all_data:
    for tag in item["tags"]:
        rows.append({
            "quote": item["quote"],
            "author": item["author"],
            "tag": tag,
            "about": item["about"]
        })

df2 = pd.DataFrame(rows)
df2.head(2)

,quote,author,tag,about
0,“The world as we have created it is a process ...,Albert Einstein,change,"In 1879, Albert Einstein was born in Ulm, Germ..."
1,“The world as we have created it is a process ...,Albert Einstein,deep-thoughts,"In 1879, Albert Einstein was born in Ulm, Germ..."

In [37]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   quote   121 non-null    object
 1   author  121 non-null    object
 2   tag     121 non-null    object
 3   about   121 non-null    object
dtypes: object(4)
memory usage: 3.9+ KB

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   quote   50 non-null     object
 1   author  50 non-null     object
 2   tags    50 non-null     object
 3   about   50 non-null     object
dtypes: object(4)
memory usage: 1.7+ KB

In [39]:
df3 = df.explode("tags")

df3.rename(columns={"tags": "tag"}, inplace=True)

df3.head()

,quote,author,tag,about
0,“The world as we have created it is a process ...,Albert Einstein,change,"In 1879, Albert Einstein was born in Ulm, Germ..."
0,“The world as we have created it is a process ...,Albert Einstein,deep-thoughts,"In 1879, Albert Einstein was born in Ulm, Germ..."
0,“The world as we have created it is a process ...,Albert Einstein,thinking,"In 1879, Albert Einstein was born in Ulm, Germ..."
0,“The world as we have created it is a process ...,Albert Einstein,world,"In 1879, Albert Einstein was born in Ulm, Germ..."
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,abilities,See also: Robert GalbraithAlthough she writes ...